user_name = input("Enter your name: ")
user_age = int(input("Enter your age: "))
user_college = input("Enter your college name: ")
user_cgpa = float(input("Enter your cgpa: "))
print("---------------------------------------")
print("         OFFICIAL STUDENT ID          ")
print("---------------------------------------")
print(f"Name:  {user_name.upper()}")
print(f"Age: {user_age}")
print(f"College: {user_college}")
print(f"CGPA: {user_cgpa}")
print("---------------------------------------")
print("Verification: PENDING")
